package com.demo.components.mybatis.codegen.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author WUDE
 * @Datetime @mbg.generated 2021-08-14 20:25:13
 * @Table t_user
 */
public class User {
    /**
     * 主键: id
     * 
     * @mbg.generated 2021-08-14 20:25:13
     */
    private Long id;

    /**
     * 用户名: username
     * 
     * @mbg.generated 2021-08-14 20:25:13
     */
    private String username;

    /**
     * 邮箱: email
     * 
     * @mbg.generated 2021-08-14 20:25:13
     */
    private String email;

    /**
     * 状态: status
     * 
     * @mbg.generated 2021-08-14 20:25:13
     */
    private Integer status;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2021-08-14 20:25:13
     */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2021-08-14 20:25:13
     */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}