# https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/current/reference/html/spring-cloud-stream.html#multiple-systems
spring:
  #  rabbitmq:
  #    host: 192.168.40.161
  #    port: 5672
  #    username: admin
  #    password: admin
  #    virtual-host: /ddmc
  ######
  cloud:
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: mq1pub.te.test.srv.mc.dd
                port: 5672
                username: admin
                password: 1234qwer
                virtual-host: /
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: mq1pub.te.test.srv.mc.dd
                port: 5672
                username: admin
                password: 1234qwer
                virtual-host: /

        rocket:
          type: rocketmq
      bindings:
        inputDemo_1:
          binder: rabbit1
          destination: demoExchange_1
          group: demoGroup_1
          cousumer:
            max-attempts: 2
            concurrency: 2
        inputDemo_2:
          binder: rabbit2
          destination: demoExchange_2
          group: demoGroup_2
          cousumer:
            max-attempts: 2
            concurrency: 2

        outputSyncProductInfo2Station:
          destination: SyncProductInfo2Station_Topic
          content-type: application/json
          binder: rocket

        outputDemo_1:
          binder: rabbit1
          destination: demoExchange_1
          content-type: application/json
          producer:
            delayed-exchange: false
        outputDemo_2:
          binder: rabbit2
          destination: demoExchange_2
          content-type: application/json
          producer:
            delayed-exchange: false

        inputSyncProductInfo2Station:
          binder: rocket
          destination: SyncProductInfo2Station_Topic
          group: SyncProductInfo2Station_Group
          content-type: application/json
          consumer:
            concurrency: 1

      rabbit:
        bindings:
          inputDemo_1:
            consumer:
              max-concurrency: 3
              republish-to-dlq: true
              auto-bind-dlq: true
              binding-routing-key: demoExchange_1
              dead-letter-exchange: demoExchange_1.DLX
              dlq-dead-letter-exchange: demoExchange_1.DLX
              dead-letter-exchange-type: direct
              dead-letter-routing-key: demoGroup_1
              dead-letter-queue-name: demoExchange_1.demoGroup_1.DLQ
          inputDemo_2:
            consumer:
              max-concurrency: 3
              republish-to-dlq: true
              auto-bind-dlq: true
              binding-routing-key: demoExchange_2
              dead-letter-exchange: demoExchange_2.DLX
              dlq-dead-letter-exchange: demoExchange_2.DLX
              dead-letter-exchange-type: direct
              dead-letter-routing-key: demoGroup_2
              dead-letter-queue-name: demoExchange_2.demoGroup_2.DLQ
      default-binder: rabbit1

      rocketmq:
        binder:
          #          name-server: rmq1pub.tsht3.mc.ops:9876
          name-server: 127.0.0.1:9876


