rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: rocketProducerGroup
    send-message-timeout: 3000


  # 自定义配置
  topic:
    demoTopic: demo-topic
    userTopic: user-topic

another:
  rocketmq:
    name-server: rmq1pub.tsht3.mc.ops:9876
    producer:
      group: anotherRocketProducerGroup
      send-message-timeout: 3000
    topic:
      userTopic: another-user-topic