spring:
  redis:
    # spring-data-redis默认配置格式
    cluster:
      nodes: 127.0.0.1:6000,127.0.0.1:7000,127.0.0.1:8000
      max-redirects: 8
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 5
        max-wait: 10000
    # 自定义redis配置, 配置格式和spring-data-redis一致
    custom:
      cluster:
        nodes: 127.0.0.1:6000,127.0.0.1:7000,127.0.0.1:8000
        max-redirects: 1
      jedis:
        pool:
          max-active: 1
          max-idle: 1
          min-idle: 1
          max-wait: 10

