package com.demo.components.shardingjdbc.dao;

import com.demo.components.base.dao.BaseDao;
import com.demo.components.shardingjdbc.model.OrderModel;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author WUDE
 * @Datetime 2021-08-22 14:06:05
 * @mbg.generated 2021-08-22 14:06:05
 */
@Repository
public interface OrderModelDao extends BaseDao<OrderModel, String> {
}