database:
  config:
    ds_0:
      url: jdbc:mysql://localhost:3306/shading_db_0?useUnicode=truecharacterEncoding=UTF-8
      username: root
      password: root
      initalSize: 1
      minIdle: 1
      maxActive: 5
      maxWait: 100
      driverClassName: com.mysql.jdbc.Driver
    ds_1:
      url: jdbc:mysql://localhost:3306/shading_db_0?useUnicode=truecharacterEncoding=UTF-8
      username: root
      password: root
      initalSize: 1
      minIdle: 1
      maxActive: 5
      maxWait: 100
      driverClassName: com.mysql.jdbc.Driver