database:
  config:
    ds_0:
      url: jdbc:mysql://localhost:3306/ds_0?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      initalSize: 1
      minIdle: 1
      maxActive: 5
      maxWait: 100
      driverClassName: com.mysql.jdbc.Driver
    ds_1:
      url: jdbc:mysql://localhost:3306/ds_1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      initalSize: 1
      minIdle: 1
      maxActive: 5
      maxWait: 100
      driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

