package com.demo.components.mybatis.codegen.dao;

import com.demo.components.base.dao.BaseDao;
import com.demo.components.mybatis.codegen.model.User;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author WUDE
 * @Datetime 2021-08-14 20:25:13
 * @mbg.generated 2021-08-14 20:25:13
 */
@Repository
public interface UserDao extends BaseDao<User, Long> {
}