package com.demo.components.mybatis.codegen.dao;

import com.demo.components.base.dao.BaseDao;
import com.demo.components.mybatis.codegen.model.User;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-08-20 13:49:46
 * @mbg.generated 2019-08-20 13:49:46
 */
@Repository
public interface UserDao extends BaseDao<User, Long> {
}