elasticsearch:
  rest:
    schema: http
    #    servers: 127.0.0.1:9201;127.0.0.1:9202
    servers: es2search.te.test.srv.mc.dd:9200
    connectTimeout: 1
    socketTimeout: 1
    connectPoolingEnabled: true
    connectionRequestTimeout: 1
    maxTotal: 5
    defaultMaxPerRoute: 5

server:
  port: 9898