elasticsearch:
  config:
    clusters:
      default:
        schema: http
#        servers: 127.0.0.1:9201;127.0.0.1:9202
        servers: 127.0.0.1:9200
        connectTimeout: 1
        socketTimeout: 1
        connectPoolingEnabled: true
        connectionRequestTimeout: 1
        maxTotal: 100
        defaultMaxPerRoute: 100
      cluster2:
        schema: http
        servers: es2search.ye.test.srv.mc.dd:9200
        connectTimeout: 1
        socketTimeout: 1
        connectPoolingEnabled: true
        connectionRequestTimeout: 1
        maxTotal: 100
        defaultMaxPerRoute: 100
server:
  port: 9898