@startuml
skinparam ConditionEndStyle diamond
start
:计算OD点距离;
if(热点块本地缓存加载好\n结构:key-(key-value)) then (no)
	#pink:现有逻辑查询最近link;
else (yes)
	: OD点取左上点映射计算热点块缓存key;
	: 热点块本地缓存获取;
	if (热点块缓存存在) then (no)
		#pink:现有逻辑查询最近link;
	else (yes)
		: O/D点圆周取整精确查询link;
		if (精确查询到link) then (no)
			if (点匹配到热点缓存内AOI-(AOI-Rtree)) then (no)
				: 热点缓存内查询点最近link-(Link-Rtree);
				if (查询到最近link) then (no)
					#pink:现有逻辑查询最近link;
				else (yes)

				endif;
			else (yes)
			    : 获取匹配link;
			endif;
		else (yes)

		endif
	endif
endif
: 查询label;
: 计算距离;
stop

@enduml