@startuml
skinparam ConditionEndStyle diamond
start
:点绑link;
:经纬度坐标圆周取整;
:本地缓存查找精确点link;
if (本地缓存查找到link) then (no)
    : 热点块缓存查找匹配link;
    if (本地热点缓存块加载好) then (no)
        #pink:现有逻辑查询最近link;
    else (yes)
        : 点坐标映射左上角计算热点块本地缓存key;
        : 获取本地缓存热点块数据;
        if (热点块缓存数据存在) then (no)
            #pink:现有逻辑查询最近link;
        else (yes)
            partition #lightyellow "AOI策略-(AOI-Rtree)" {
                : 点匹配AOI查询;
                if (AOI匹配到) then (no)
                    partition #lightgray "LineString Rtree查找最近link" {
                        : 本地Rtree查找最近边;
                        if (查找到最近边) then (no)
                            #pink:现有逻辑查询最近link;
                        else (yes)

                        endif
                    }
                else (yes)

                endif
            }
        endif;
    endif
else (yes)
endif;
:点匹配link;
stop;

@enduml