spring:
  application:
    name: rabbitmq-integration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /ddmc
    connection-timeout: 60000
    redeclare: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 7171
  shutdown: graceful
